stompy:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10
        extra_joints:
            - name: 'fl_ankle'
            - name: 'fl_foot'
            - name: 'fl_pad'
            - name: 'fr_ankle'
            - name: 'fr_foot'
            - name: 'fr_pad'
            - name: 'ml_ankle'
            - name: 'ml_foot'
            - name: 'ml_pad'
            - name: 'mr_ankle'
            - name: 'mr_foot'
            - name: 'mr_pad'
            - name: 'rl_ankle'
            - name: 'rl_foot'
            - name: 'rl_pad'
            - name: 'rr_ankle'
            - name: 'rr_foot'
            - name: 'rr_pad'

    fl:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - fl_hip
            - fl_thigh
            - fl_knee

        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.1
            fl_hip:
                goal: 0.1
            fl_thigh:
                goal: 0.1
            fl_knee:
                goal: 0.1

        gains:
            fl_hip: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            fl_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            fl_knee: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

        state_publish_rate: 10
        action_monitor_rate: 10

    fr:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - fr_hip
            - fr_thigh
            - fr_knee

        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.1
            fr_hip:
                goal: 0.1
            fr_thigh:
                goal: 0.1
            fr_knee:
                goal: 0.1

        gains:
            fr_hip: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            fr_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            fr_knee: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

        state_publish_rate: 10
        action_monitor_rate: 10

    ml:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - ml_hip
            - ml_thigh
            - ml_knee

        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.1
            ml_hip:
                goal: 0.1
            ml_thigh:
                goal: 0.1
            ml_knee:
                goal: 0.1

        gains:
            ml_hip: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            ml_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            ml_knee: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

        state_publish_rate: 10
        action_monitor_rate: 10

    mr:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - mr_hip
            - mr_thigh
            - mr_knee

        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.1
            mr_hip:
                goal: 0.1
            mr_thigh:
                goal: 0.1
            mr_knee:
                goal: 0.1

        gains:
            mr_hip: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            mr_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            mr_knee: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

        state_publish_rate: 10
        action_monitor_rate: 10

    rl:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - rl_hip
            - rl_thigh
            - rl_knee

        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.1
            rl_hip:
                goal: 0.1
            rl_thigh:
                goal: 0.1
            rl_knee:
                goal: 0.1

        gains:
            rl_hip: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            rl_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            rl_knee: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

        state_publish_rate: 10
        action_monitor_rate: 10

    rr:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - rr_hip
            - rr_thigh
            - rr_knee

        constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.1
            rr_hip:
                goal: 0.1
            rr_thigh:
                goal: 0.1
            rr_knee:
                goal: 0.1

        gains:
            rr_hip: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            rr_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            rr_knee: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

        state_publish_rate: 10
        action_monitor_rate: 10


# Position Controllers ---------------------------------------
    fl_calf_controller:
        type: effort_controllers/JointPositionController
        joint: fl_calf
        pid: {p: 105075.9, i: 0, d: 0}

    fr_calf_controller:
        type: effort_controllers/JointPositionController
        joint: fr_calf
        pid: {p: 105075.9, i: 0, d: 0}

    ml_calf_controller:
        type: effort_controllers/JointPositionController
        joint: ml_calf
        pid: {p: 105075.9, i: 0, d: 0}

    mr_calf_controller:
        type: effort_controllers/JointPositionController
        joint: mr_calf
        pid: {p: 105075.9, i: 0, d: 0}

    rl_calf_controller:
        type: effort_controllers/JointPositionController
        joint: rl_calf
        pid: {p: 105075.9, i: 0, d: 0}

    rr_calf_controller:
        type: effort_controllers/JointPositionController
        joint: rr_calf
        pid: {p: 105075.9, i: 0, d: 0}
