stompyleg:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: 'joint_state_controller/JointStateController'
        publish_rate: 50
        extra_joints:
            - name: 'stompyleg__fl__calf_lower_to_ankle'
            - name: 'stompyleg__fl__ankle_to_foot'
            - name: 'stompyleg__fl__foot_to_pad'

    fl:
        type: 'effort_controllers/JointTrajectoryController'
        joints:
            - stompyleg__body_to_fl
            - stompyleg__fl__hip_to_thigh
            - stompyleg__fl__thigh_to_calf_upper

        constraints:
            stompyleg__body_to_fl:
                goal: 0.1
            stompyleg__fl__hip_to_thigh:
                goal: 0.1
            stompyleg__fl__thigh_to_calf_upper:
                goal: 0.1

        gains:
            stompyleg__body_to_fl: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}
            stompyleg__fl__hip_to_thigh: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}
            stompyleg__fl__thigh_to_calf_upper: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

    hip_controller:
        type: 'effort_controllers/JointPositionController'
        joint: 'stompyleg__body_to_fl'
        pid: {p: 480000, i: 50.0, d: 30.0, i_clamp: 10.0}

    thigh_controller:
        type: 'effort_controllers/JointPositionController'
        joint: 'stompyleg__fl__hip_to_thigh'
        pid: {p: 800000, i: 50.0, d: 30.0, i_clamp: 10.0}

    knee_controller:
        type: 'effort_controllers/JointPositionController'
        joint: 'stompyleg__fl__thigh_to_calf_upper'
        pid: {p: 360000, i: 50.0, d: 30.0, i_clamp: 10.0}

    calf_controller:
        type: 'effort_controllers/JointPositionController'
        joint: 'stompyleg__fl__calf_upper_to_calf_lower'
        pid: {p: 105075.9, i: 0.0, d: 0.0}
