stompyleg:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10

# Position Controllers ---------------------------------------
    hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompyleg__body_to_fl
        pid: {p: 100.0, i: 0.0, d: 0.0}

    thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompyleg__fl__hip_to_thigh
        pid: {p: 100.0, i: 0.0, d: 0.0}

    knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompyleg__fl__thigh_to_calf_upper
        pid: {p: 100.0, i: 0.0, d: 0.0}
