stompy:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10

# Position Controllers ---------------------------------------
    fl_hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__body_to_fl
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    fl_thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__fl__hip_to_thigh
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    fl_knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__fl__thigh_to_calf_upper
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    fr_hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__body_to_fr
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    fr_thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__fr__hip_to_thigh
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    fr_knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__fr__thigh_to_calf_upper
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    ml_hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__body_to_ml
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    ml_thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__ml__hip_to_thigh
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    ml_knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__ml__thigh_to_calf_upper
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    mr_hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__body_to_mr
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    mr_thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__mr__hip_to_thigh
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    mr_knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__mr__thigh_to_calf_upper
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    rl_hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__body_to_rl
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    rl_thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__rl__hip_to_thigh
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    rl_knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__rl__thigh_to_calf_upper
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    rr_hip_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__body_to_rr
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    rr_thigh_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__rr__hip_to_thigh
        pid: {p: 3000.0, i: 50.0, d: 500.0}

    rr_knee_controller:
        type: effort_controllers/JointPositionController
        joint: stompy__rr__thigh_to_calf_upper
        pid: {p: 3000.0, i: 50.0, d: 500.0}
