stompyleg:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: 'joint_state_controller/JointStateController'
        publish_rate: 10
        extra_joints:
            - name: 'stompyleg__fl__calf_lower_to_ankle'
            - name: 'stompyleg__fl__ankle_to_foot'

# Position Controllers ---------------------------------------
#    leg_controller:
#        type: 'position_controllers/JointTrajectoryController'
#        joints:
#            - 'stompyleg__body_to_fl'
#            - 'stompyleg__fl__hip_to_thigh'
#            - 'stompyleg__fl__thigh_to_calf_upper'

    hip_controller:
        type: 'position_controllers/JointPositionController'
        joint: 'stompyleg__body_to_fl'

    thigh_controller:
        type: 'position_controllers/JointPositionController'
        joint: 'stompyleg__fl__hip_to_thigh'

    knee_controller:
        type: 'position_controllers/JointPositionController'
        joint: 'stompyleg__fl__thigh_to_calf_upper'

    calf_controller:
        type: 'effort_controllers/JointPositionController'
        joint: 'stompyleg__fl__calf_upper_to_calf_lower'
        pid: {p: 105075.9, i: 0.0, d: 0.0}
